[features]
seeds = false
skip-lint = false
[programs.mainnet]
btc_relay = "3KHSHFpEK6bsjg3bqcxQ9qssJYtRCMi2S9TYVe4q6CQc"
[programs.localnet]
btc_relay = "3KHSHFpEK6bsjg3bqcxQ9qssJYtRCMi2S9TYVe4q6CQc"
[programs.devnet]
btc_relay = "3KHSHFpEK6bsjg3bqcxQ9qssJYtRCMi2S9TYVe4q6CQc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/mainnet.key"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
